name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Setup JDK"
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: "zulu"

      - name: "Build with Gradle"
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build