name: Publish

on:
  push:
    branches: [ "master" ]

  release:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3

      - name: "Setup JDK"
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: "zulu"

      - name: "Generate Dokka"
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: dokkaHtml

      - name: "Publish Documentation"
        uses: crazy-max/ghaction-github-pages@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: build/dokka/html

      - name: "Publish with Gradle"
        uses: gradle/gradle-build-action@v2
        env:
          # ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          # ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_mavenPassword: ${{ secrets.MAVEN_PASSWORD }}
        with:
          arguments: test publish

      - name: "Publish Test Results"
        uses: codecov/codecov-action@v3
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
